### ISSUE TITLE
"add swapfile to /etc/fstab" is not idempotent

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-swapfile#1]
The `mount` module always reports changes.

Could be resolved by using:
```
action: lineinfile dest=/etc/fstab regexp="swap" line="/swap none swap sw 0 0" state=present
```
but I don't really like that. Suggestions?

**Comment by ypid** [comment]
Seems to be an upstream issue in the module as reported by you :smile:
Issue for reference: https://github.com/ansible/ansible-modules-core/issues/1868
