### ISSUE TITLE
unable to download from galaxy

### ISSUE THREAD

**Issue by michaelpporter** [Oefenweb/ansible-swapfile#11]
When I run `ansible-galaxy install oefenweb.swapfile`

 I get the error 

```bash
- downloading role 'swapfile', owned by oefenweb
 [WARNING]: - oefenweb.swapfile was NOT installed successfully: - sorry,
oefenweb.swapfile was not found on https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

ansible-galaxy --version
ansible-galaxy 2.5.0

I am able to get other roles.

**Comment by tersmitten** [comment]
Can you give tersmitten.swapfile a try?

**Comment by tersmitten** [comment]
Can you give tersmitten.swapfile a try?

**Comment by tersmitten** [comment]
All my old roles are (were) under [`tersmitten`](https://galaxy.ansible.com/tersmitten), my new one under [`Oefenweb`](https://galaxy.ansible.com/Oefenweb). But it looks like something changed in galaxy...

**Comment by iBelieve** [comment]
Looks like this is fixed now. The old role name `tersmitten.swapfile` no longer works, and the new role name `oefenweb.swapfile` works now. See https://galaxy.ansible.com/Oefenweb/swapfile

**Comment by michaelpporter** [comment]
`ansible-galaxy install oefenweb.swapfile` works for me. Thank you.

**Comment by sebastiaanluca** [comment]
Could this still be an issue? Getting the following error when trying to fetch the latest release:

```
downloading role 'swapfile', owned by oefenweb
 [WARNING]: - oefenweb.swapfile was NOT installed successfully: - the specified version (v2.0.17) of oefenweb.swapfile was not found in the list of available versions
```

2.0.14 (3 tags earlier) is the latest that pops up in the list following the error.

**Comment by tersmitten** [comment]
There was an issue on our side, can you try to install `v2.0.18`?

**Comment by sebastiaanluca** [comment]
Works, thanks!
