### ISSUE TITLE
Swapfile size not changed

### ISSUE THREAD

**Issue by mkllnk** [Oefenweb/ansible-swapfile#14]
Once you have a file at `/swap`, it is never changed. Changing `swapfile_size` triggers `fallocate`, but it doesn't do anything.
```
TASK [oefenweb.swapfile : write swap file] ************************************************************************************************************************************************************************
Wednesday 02 January 2019  16:16:44 +1100 (0:00:00.701)       0:00:01.635 ***** 
ok: [local_vagrant] => {"changed": false, "cmd": ["fallocate", "-l", "2G", "/swap"], "rc": 0, "stdout": "skipped, since /swap exists", "stdout_lines": ["skipped, since /swap exists"]}
```
```
$ ls -lh /swap 
-rw------- 1 root root 1.0G Aug  3 05:52 /swap
```

**Comment by tersmitten** [comment]
Can you propose a fix?

**Comment by mkllnk** [comment]
I'm not sure. It's not simple and there are several options.

We can't change the size of a swap file while it is in use. Extending may work, but truncating may lead to data loss. So one idea would be to turn the swap off:
```
if /swap exists:
swapoff
truncate -s $size /swap
mkswap /swap
swapon
```

The risk is that the server doesn't have enough memory in the moment and crashes on `swapoff`. If we wanted to transition more safely, we need two files. It could look like this:

```
if /swap exists:
tmpfile = $(mktemp)
fallocate -l $size $tmpfile
swapon $tmpfile
swapoff /swap
truncate -s $size /swap
mkswap /swap
swapon /swap
swapoff $tmpfile
```

**Comment by sebastiaanluca** [comment]
Can confirm this issue. Ubuntu installed with 2GB /swapfile. Changing to 8GB and provisioning using this role doesn't increase its size.

**Comment by tersmitten** [comment]
Due to inactivity
