### ISSUE TITLE
Check available disk space before creating swapfile

### ISSUE THREAD

**Issue by Matt-Yorkley** [Oefenweb/ansible-swapfile#15]
Just a heads-up that `fallocate` will blindly (attempt to) create a file that is larger than the available space on the disk, without doing any checks first to see if there is enough space.

See some discussion here: https://stackoverflow.com/questions/32799252/why-fallocate-on-linux-creates-a-non-empty-file-when-it-has-not-enough-space

I encountered this recently (adding swap when the disk was too full) and it led to some _really nasty_ data corruption.

Maybe a quick task to check if the amount being allocated is less than the available disk space would be a nice safety feature?

**Comment by tersmitten** [comment]
I'm open to this idea. How would you implement the check?
