### ISSUE TITLE
Add support for dd

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-swapfile#6]
For filesystems that do not support `fallocate`

**Comment by cleberjsantos** [comment]
@tersmitten I'm of agreement, but this Ansible role is just to manage a swap file in Debian-like systems :/

**Comment by tersmitten** [comment]
Yes it is, but the file system is the problem. Ext3 and reiserfs don't support fallocate

**Comment by ypid** [comment]
@tersmitten I think you can deprecate your role in favor to [debops.swapfile](https://github.com/debops/ansible-swapfile). It does already support `dd` [see tasks file](https://github.com/debops/ansible-swapfile/blob/b42f67a6573299c25d09fa830eda41af96baa718/tasks/main.yml#L31). What do you think? Do you use DebOps or is there something missing for you?

**Comment by tersmitten** [comment]
You're probably right, but I find the DebOps roles (too) complex for us.

**Comment by ypid** [comment]
Some roles a a bit overengineering but every one of them which I have looked into is very well written and has sane defaults. So you can start of easy but the role allows to make hard things easy as well.

**Comment by tersmitten** [comment]
They're indeed well written.

**Comment by tersmitten** [comment]
Closing for now as we don't use `ext3` and `reiserfs`
